### ISSUE TITLE
Font not universal

### ISSUE THREAD

**Issue by gezakerecsenyi** [palkerecsenyi/kwestgame#2]
Embed the font into the HTML5 as a symbol

**Comment by palkerecsenyi** [comment]
Download font on clients for now, may add as web font import if possible.

**Comment by palkerecsenyi** [comment]
Will use Google fonts https://fonts.google.com/specimen/Press+Start+2P

**Comment by palkerecsenyi** [comment]
Using typekit, will host through http not ssl. not github

**Comment by palkerecsenyi** [comment]
https://typekit.com/fonts/hydrophilia
